### ISSUE TITLE
站点样式

### ISSUE THREAD

**Issue by zuoer96** [Yiov/vitepress-doc#2]
按照[文档](https://vitepress.yiov.top/assets.html) 搭建vitepress后，
样式无法和该站点一样
比如:::tip 显示

![image](https://github.com/Yiov/vitepress-doc/assets/31268184/c7818fa5-1bd0-44ba-8709-61912e43425b)

然后高亮也不一样
![image](https://github.com/Yiov/vitepress-doc/assets/31268184/eebc2b80-26cb-4578-b9c4-be21ca3c1b78)
要怎么调整为和你的一样？

**Comment by Yiov** [comment]
那就是css样式丢失了，你的base配置错误

看了下你的config.ts文件，base改成如下

```
base: '/docs/', //网站部署到github的docs这个仓库里
```

你的仓库名是 `zuoer96.github.io` 或者 网站服务器根目录，那么配置为 `base: '/', `

你的仓库名是 `docs`，那么配置为 `base: '/docs/',`

必须要对应

**Comment by zuoer96** [comment]
> 那就是css样式丢失了，你的base配置错误
> 
> 看了下你的config.ts文件，base改成如下
> 
> ```
> base: '/docs/', //网站部署到github的docs这个仓库里
> ```
> 
> 你的仓库名是 `zuoer96.github.io` 或者 网站服务器根目录，那么配置为 `base: '/', `
> 
> 你的仓库名是 `docs`，那么配置为 `base: '/docs/',`
> 
> 必须要对应

我[参考快速上手](https://vitepress.yiov.top/getting-started.html)重新拉取了个demo，加上了/viteperss/
在本地启动的效果，和部署后的是一致的吧，本地没有看到那个漂亮的样式
![image](https://github.com/Yiov/vitepress-doc/assets/31268184/843e795a-11b6-4bf3-899c-7e78c5abbddd)

**Comment by Yiov** [comment]
只要仓库名一致，部署就是一致的，现在的官方的版本是1.00-rc.12

而我的版本是1.00-beta.5，样式个最新的是不一样了

现在官方文档样式，就是你图片上的这样的

https://vitepress.dev/guide/markdown#custom-containers

**Comment by zuoer96** [comment]
> 只要仓库名一致，部署就是一致的，现在的官方的版本是1.00-rc.12
> 
> 而我的版本是1.00-beta.5，样式个最新的是不一样了
> 
> 现在官方文档样式，就是你图片上的这样的
> 
> https://vitepress.dev/guide/markdown#custom-containers

明白了，谢谢
