### ISSUE TITLE
佬，深浅模式切换动画过渡可以做个教程吗

### ISSUE THREAD

**Issue by qihaimi** [Yiov/vitepress-doc#22]
https://vitepress.dev/zh/guide/extending-default-theme#on-appearance-toggle
官网的文档，没有任何基础，找了一天，没找着，求求了

**Comment by Yiov** [comment]
之前我也看过，在其中一个 [PR #2347](https://github.com/vuejs/vitepress/pull/2347)，这个过渡方案没有被采用

只是给了个组件示例，然后写在了文档中，并不是拿来就用，需要自己编写

在另一个 [Discussions/4012](https://github.com/vuejs/vitepress/discussions/4012) 中，有一个 @shellRaining 演示的 [例子](https://github.com/shellRaining/blog/blob/b751cdfac3d7b3ad205e0aac226c67d4f436628a/theme/Home/AppearanceSwitcher.vue)，自定义组件可以实现，但是它是一个单独的按钮，并不能与现有的深浅模式开关合并

这是他的一个demo：https://shellraining.xyz/

要实现，只能先隐藏默认的深浅开关，然后自行编写一个新的开关组件，再将组件用在 插槽 `nav-bar-content-after` 上，基本上是可以的

---

这个确实是花里胡哨的东西，所以官方也没有想加入。我的能力有限，可能也不会编写

你可以参照着他的示例，修改来达到简单的效果

**Comment by shellRaining** [comment]
https://shellraining.xyz/docs/tools/vitepress/dark.html

这个部分我看了蛮久的，写成了一篇博客，也许能帮到你。不过 view transition API 确实有点神奇，到现在还没有完全摸透，现在暂时没有时间搞这个了

**Comment by Yiov** [comment]
哇哦，本人来了，我又对照着看了一遍，将官方代码 `enableTransitions` 相关参数删除竟然可以了

不过只能使用默认的主题布局 Layout，[简单写了一个示例](https://vitepress.yiov.top/layout.html#%E8%A7%86%E5%9B%BE%E8%BF%87%E6%B8%A1)

@qihaimi 可以尝试感受一下
